package code

// 定义了各种不同的错误码
const (
	HTTP_OK int = 0
	HTTP_PARAMS_NOTEXISTS int = 10001
	HTTP_PARAMS_ERROR int = 10002

	HTTP_SYMBOL_MATCHINIG_OPEN_REPEAT = 20001
	HTTP_SYMBOL_MATCHINIG_OPEN_ERROR = 20002
	HTTP_SYMBOL_NOTIN_ALLOWLIST = 20003

	HTTP_SYMBOL_MATCHINIG_CLOSE_REPEAT = 30001

	HTTP_ORDER_HANDLE_ERROR = 40001
	HTTP_ORDER_HANDLE_PRICE_ISZERO = 40002
	HTTP_ORDER_HANDLE_AMOUNT_ISZERO = 40003
	HTTP_ORDER_HANDLE_ACTION_ERROR = 40004
	HTTP_ORDER_HANDLE_TYPE_ERROR = 40005
	HTTP_ORDER_HANDLE_SIDE_ERROR = 40006
)

type HttpResult struct {
	Code int `json:"code"` // 状态码
	Msg string `json:"msg"` // 消息
	Data interface{} `json:"data"` // 返回的数据，一般来说是json对象
}